import {
  formatDateTime,
  formatMoney,
  getSettlementStatusLabel,
  getSettlementStatusTone,
  readPageMessages,
  readSearchFilters,
  type SearchParamsInput,
} from "@/app/admin/support";
import {
  AdminPageHeader,
  FlashMessage,
  LabeledField,
  StatCard,
  StatusBadge,
  buttonClass,
  panelClass,
  selectClass,
  tableWrapperClass,
} from "@/app/admin/ui";
import {
  markSettlementPaidAction,
  runFinanceMaintenanceAction,
} from "@/app/admin/actions";
import {
  MerchantLedgerDirection,
  MerchantLedgerEntryType,
  PaymentRefundStatus,
  PaymentStatus,
} from "@/generated/prisma/enums";
import { requireAdminPermission } from "@/lib/admin-session";
import type { Locale } from "@/lib/i18n";
import { getCurrentLocale } from "@/lib/i18n-server";
import { getMerchantDisplayName } from "@/lib/merchant-profile-completion";
import { hasPermission } from "@/lib/rbac";
import { getPrismaClient } from "@/lib/prisma";

function parseDateStart(value: string) {
  if (!value) {
    return new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  }

  return new Date(`${value}T00:00:00.000+08:00`);
}

function parseDateEnd(value: string) {
  if (!value) {
    return new Date();
  }

  return new Date(`${value}T23:59:59.999+08:00`);
}

function formatDay(value: Date, locale: Locale = "zh") {
  return new Intl.DateTimeFormat(locale === "en" ? "en-US" : "zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(value);
}

function getLedgerTone(direction: MerchantLedgerDirection) {
  return direction === MerchantLedgerDirection.CREDIT ? "success" : "danger";
}

function getLedgerTypeLabel(type: MerchantLedgerEntryType, locale: Locale = "zh") {
  switch (type) {
    case MerchantLedgerEntryType.PAYMENT_CAPTURE:
      return locale === "en" ? "Payment Capture" : "收款入账";
    case MerchantLedgerEntryType.PAYMENT_FEE:
      return locale === "en" ? "Payment Fee" : "手续费";
    case MerchantLedgerEntryType.SETTLEMENT_PAYOUT:
      return locale === "en" ? "Settlement Payout" : "结算打款";
    default:
      return type;
  }
}

function getLedgerDirectionLabel(direction: MerchantLedgerDirection, locale: Locale = "zh") {
  return direction === MerchantLedgerDirection.CREDIT
    ? locale === "en"
      ? "Credit"
      : "入账"
    : locale === "en"
      ? "Debit"
      : "出账";
}

export default async function AdminFinancePage({
  searchParams,
}: {
  searchParams?: SearchParamsInput;
}) {
  const session = await requireAdminPermission("finance:read");
  const canWriteFinance = hasPermission(session.adminUser.role, "finance:write");
  const prisma = getPrismaClient();
  const locale = await getCurrentLocale();
  const filters = await readSearchFilters(searchParams, ["merchantCode", "dateFrom", "dateTo"]);
  const messages = await readPageMessages(searchParams);
  const content =
    locale === "en"
      ? {
          eyebrow: "Finance",
          title: "Finance center",
          description:
            "This page is read-oriented. Reconciliation, settlement summaries, and balance snapshots are generated by the finance worker or explicit sync actions to avoid implicit writes during page rendering.",
          sync: "Sync Finance Data Now",
          openOrders: "Open Order Center",
          income: "Collection",
          incomeDetail: "Successful collection amount within the selected range",
          fee: "Fees",
          feeDetail: "Accrued service fees",
          refund: "Refund",
          refundDetail: "Successful refund amount within the selected range",
          net: "Net",
          netDetail: "Net inflow after fees and refunds",
          pendingSettlement: "Pending Settlement",
          pendingSettlementDetail: "Current settlement balance awaiting payout",
          filterTitle: "Filters",
          merchant: "Merchant",
          allMerchants: "All Merchants",
          dateFrom: "Start Date",
          dateTo: "End Date",
          updateView: "Refresh View",
          reconciliationEyebrow: "Reconciliation",
          reconciliationTitle: "Daily reconciliation",
          noReconciliation: "No reconciliation data is available in the current date range.",
          settlementsEyebrow: "Settlements",
          settlementsTitle: "Settlements",
          noSettlements: "No settlement records yet. Run the finance worker or click \"Sync Finance Data Now\" first.",
          markPaid: "Mark as Paid",
          balanceEyebrow: "Balance Snapshots",
          balanceTitle: "Balance snapshots",
          noBalance: "No balance snapshots yet. Run the finance worker or sync manually first.",
          ledgerEyebrow: "Ledger",
          ledgerTitle: "Ledger entries",
          noLedger: "No ledger entries yet.",
          reconciliationDateCol: "Date",
          merchantCol: "Merchant",
          incomeCountCol: "Collections",
          refundCountCol: "Refunds",
          incomeAmountCol: "Collection Amount",
          feeAmountCol: "Fees",
          refundAmountCol: "Refund Amount",
          netAmountCol: "Net Amount",
          settlementDateCol: "Settlement Date",
          grossAmountCol: "Gross",
          adjustmentCol: "Adjustment",
          eligibleAtCol: "Eligible / Paid",
          statusCol: "Status",
          actionCol: "Action",
          paidAtPrefix: "Paid",
          balanceDateCol: "Snapshot Date",
          openingBalanceCol: "Opening",
          expenseCol: "Debit",
          closingBalanceCol: "Closing",
          ledgerTimeCol: "Occurred At",
          typeCol: "Type",
          directionCol: "Direction",
          amountCol: "Amount",
          referenceCol: "Reference",
          descriptionCol: "Description",
        }
      : {
          eyebrow: "Finance",
          title: "资金中心",
          description:
            "资金页仅展示财务结果。补账、结算汇总与余额快照统一由 finance worker 或手动同步动作生成，避免页面渲染期间发生隐式写入。",
          sync: "立即同步财务数据",
          openOrders: "打开订单中心",
          income: "收款",
          incomeDetail: "筛选范围内成功收款金额",
          fee: "手续费",
          feeDetail: "已计提手续费",
          refund: "Refund",
          refundDetail: "筛选范围内成功退款金额",
          net: "净额",
          netDetail: "收款减手续费减退款后的净流入",
          pendingSettlement: "待结算",
          pendingSettlementDetail: "当前待打款的结算余额",
          filterTitle: "筛选条件",
          merchant: "商户",
          allMerchants: "全部商户",
          dateFrom: "开始日期",
          dateTo: "结束日期",
          updateView: "更新视图",
          reconciliationEyebrow: "Reconciliation",
          reconciliationTitle: "对账日报",
          noReconciliation: "当前筛选范围内没有可用对账数据。",
          settlementsEyebrow: "Settlements",
          settlementsTitle: "结算单",
          noSettlements: "当前还没有结算单。请先运行 finance worker 或点击“立即同步财务数据”。",
          markPaid: "标记已打款",
          balanceEyebrow: "Balance Snapshots",
          balanceTitle: "余额快照",
          noBalance: "当前还没有余额快照。请先运行 finance worker 或手动同步。",
          ledgerEyebrow: "Ledger",
          ledgerTitle: "资金流水",
          noLedger: "当前还没有资金流水记录。",
          reconciliationDateCol: "日期",
          merchantCol: "商户",
          incomeCountCol: "收款笔数",
          refundCountCol: "退款笔数",
          incomeAmountCol: "收款金额",
          feeAmountCol: "手续费",
          refundAmountCol: "退款金额",
          netAmountCol: "净额",
          settlementDateCol: "结算日",
          grossAmountCol: "毛收入",
          adjustmentCol: "调整金额",
          eligibleAtCol: "可打款 / 已打款",
          statusCol: "状态",
          actionCol: "操作",
          paidAtPrefix: "打款",
          balanceDateCol: "日期",
          openingBalanceCol: "期初",
          expenseCol: "支出",
          closingBalanceCol: "期末",
          ledgerTimeCol: "时间",
          typeCol: "类型",
          directionCol: "方向",
          amountCol: "金额",
          referenceCol: "关联单据",
          descriptionCol: "说明",
        };
  const dateFrom = parseDateStart(filters.dateFrom);
  const dateTo = parseDateEnd(filters.dateTo);

  const [merchants, ledgerEntries, paymentOrders, paymentRefunds, settlements, balanceSnapshots] =
    await Promise.all([
      prisma.merchant.findMany({
        orderBy: [{ code: "asc" }],
        select: {
          id: true,
          code: true,
          name: true,
        },
      }),
      prisma.merchantLedgerEntry.findMany({
        where: {
          ...(filters.merchantCode ? { merchant: { code: filters.merchantCode } } : {}),
          occurredAt: {
            gte: dateFrom,
            lte: dateTo,
          },
        },
        orderBy: [{ occurredAt: "desc" }, { createdAt: "desc" }],
        take: 200,
        include: {
          merchant: {
            select: {
              code: true,
              name: true,
            },
          },
          paymentOrder: {
            select: {
              id: true,
              externalOrderId: true,
              channelCode: true,
            },
          },
          paymentRefund: {
            select: {
              id: true,
              externalRefundId: true,
            },
          },
          settlement: {
            select: {
              id: true,
              settlementDate: true,
            },
          },
        },
      }),
      prisma.paymentOrder.findMany({
        where: {
          status: PaymentStatus.SUCCEEDED,
          paidAt: {
            gte: dateFrom,
            lte: dateTo,
          },
          ...(filters.merchantCode ? { merchant: { code: filters.merchantCode } } : {}),
        },
        select: {
          id: true,
          amount: true,
          feeAmount: true,
          netAmount: true,
          currency: true,
          paidAt: true,
          merchant: {
            select: {
              code: true,
              name: true,
            },
          },
        },
      }),
      prisma.paymentRefund.findMany({
        where: {
          status: PaymentRefundStatus.SUCCEEDED,
          refundedAt: {
            gte: dateFrom,
            lte: dateTo,
          },
          ...(filters.merchantCode ? { merchant: { code: filters.merchantCode } } : {}),
        },
        select: {
          id: true,
          amount: true,
          currency: true,
          refundedAt: true,
          merchant: {
            select: {
              code: true,
              name: true,
            },
          },
        },
      }),
      prisma.merchantSettlement.findMany({
        where: {
          ...(filters.merchantCode ? { merchant: { code: filters.merchantCode } } : {}),
          settlementDate: {
            gte: dateFrom,
            lte: dateTo,
          },
        },
        orderBy: [{ settlementDate: "desc" }, { createdAt: "desc" }],
        take: 200,
        include: {
          merchant: {
            select: {
              code: true,
              name: true,
            },
          },
        },
      }),
      prisma.merchantBalanceSnapshot.findMany({
        where: {
          ...(filters.merchantCode ? { merchant: { code: filters.merchantCode } } : {}),
          snapshotDate: {
            gte: dateFrom,
            lte: dateTo,
          },
        },
        orderBy: [{ snapshotDate: "desc" }, { createdAt: "desc" }],
        take: 200,
        include: {
          merchant: {
            select: {
              code: true,
              name: true,
            },
          },
        },
      }),
    ]);

  const reconciliationMap = new Map<
    string,
    {
      day: string;
      merchantCode: string;
      merchantName: string;
      incomeAmount: number;
      feeAmount: number;
      refundAmount: number;
      incomeCount: number;
      refundCount: number;
    }
  >();

  for (const order of paymentOrders) {
    const day = formatDay(order.paidAt ?? dateFrom, locale);
    const key = `${day}:${order.merchant.code}`;
    const current =
      reconciliationMap.get(key) ??
      {
        day,
        merchantCode: order.merchant.code,
        merchantName: getMerchantDisplayName(order.merchant.name, locale),
        incomeAmount: 0,
        feeAmount: 0,
        refundAmount: 0,
        incomeCount: 0,
        refundCount: 0,
      };
    current.incomeAmount += Number(order.amount.toString());
    current.feeAmount += Number(order.feeAmount.toString());
    current.incomeCount += 1;
    reconciliationMap.set(key, current);
  }

  for (const refund of paymentRefunds) {
    const day = formatDay(refund.refundedAt ?? dateFrom, locale);
    const key = `${day}:${refund.merchant.code}`;
    const current =
      reconciliationMap.get(key) ??
      {
        day,
        merchantCode: refund.merchant.code,
        merchantName: getMerchantDisplayName(refund.merchant.name, locale),
        incomeAmount: 0,
        feeAmount: 0,
        refundAmount: 0,
        incomeCount: 0,
        refundCount: 0,
      };
    current.refundAmount += Number(refund.amount.toString());
    current.refundCount += 1;
    reconciliationMap.set(key, current);
  }

  const reconciliationRows = Array.from(reconciliationMap.values()).sort((left, right) => {
    if (left.day !== right.day) {
      return left.day < right.day ? 1 : -1;
    }

    return left.merchantCode.localeCompare(right.merchantCode);
  });

  const totalIncome = reconciliationRows.reduce((sum, row) => sum + row.incomeAmount, 0);
  const totalFee = reconciliationRows.reduce((sum, row) => sum + row.feeAmount, 0);
  const totalRefund = reconciliationRows.reduce((sum, row) => sum + row.refundAmount, 0);
  const pendingSettlementAmount = settlements
    .filter((settlement) => settlement.status !== "PAID")
    .reduce((sum, settlement) => sum + Number(settlement.netAmount.toString()), 0);

  return (
    <div className="space-y-8">
      <AdminPageHeader
        eyebrow={content.eyebrow}
        title={content.title}
        description={content.description}
        actions={
          canWriteFinance ? (
            <form action={runFinanceMaintenanceAction}>
              <input type="hidden" name="redirectTo" value="/admin/finance" />
              <button type="submit" className={buttonClass}>
                {content.sync}
              </button>
            </form>
          ) : (
            <a href="/admin/orders" className={buttonClass}>
              {content.openOrders}
            </a>
          )
        }
      />

      <FlashMessage success={messages.success} error={messages.error} />

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        <StatCard label={content.income} value={formatMoney(totalIncome, "CNY", locale)} detail={content.incomeDetail} />
        <StatCard label={content.fee} value={formatMoney(totalFee, "CNY", locale)} detail={content.feeDetail} />
        <StatCard label={content.refund} value={formatMoney(totalRefund, "CNY", locale)} detail={content.refundDetail} />
        <StatCard
          label={content.net}
          value={formatMoney(totalIncome - totalFee - totalRefund, "CNY", locale)}
          detail={content.netDetail}
        />
        <StatCard
          label={content.pendingSettlement}
          value={formatMoney(pendingSettlementAmount, "CNY", locale)}
          detail={content.pendingSettlementDetail}
        />
      </section>

      <section className={`${panelClass} p-6`}>
        <h2 className="text-2xl font-semibold text-foreground">{content.filterTitle}</h2>
        <form className="mt-6 grid gap-4 lg:grid-cols-4">
          <LabeledField label={content.merchant}>
            <select name="merchantCode" defaultValue={filters.merchantCode} className={selectClass}>
              <option value="">{content.allMerchants}</option>
              {merchants.map((merchant) => (
                <option key={merchant.id} value={merchant.code}>
                  {merchant.code} / {getMerchantDisplayName(merchant.name, locale)}
                </option>
              ))}
            </select>
          </LabeledField>
          <LabeledField label={content.dateFrom}>
            <input name="dateFrom" type="date" defaultValue={filters.dateFrom} className={selectClass} />
          </LabeledField>
          <LabeledField label={content.dateTo}>
            <input name="dateTo" type="date" defaultValue={filters.dateTo} className={selectClass} />
          </LabeledField>
          <div className="flex items-end">
            <button type="submit" className={buttonClass}>
              {content.updateView}
            </button>
          </div>
        </form>
      </section>

      <section className={`${panelClass} p-6`}>
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-muted">{content.reconciliationEyebrow}</p>
          <h2 className="mt-2 text-2xl font-semibold text-foreground">{content.reconciliationTitle}</h2>
        </div>

        <div className={`mt-6 ${tableWrapperClass}`}>
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-[#f3e7d7] text-xs uppercase tracking-[0.18em] text-muted">
                <tr>
                  <th className="px-4 py-3">{content.reconciliationDateCol}</th>
                  <th className="px-4 py-3">{content.merchantCol}</th>
                  <th className="px-4 py-3">{content.incomeCountCol}</th>
                  <th className="px-4 py-3">{content.refundCountCol}</th>
                  <th className="px-4 py-3">{content.incomeAmountCol}</th>
                  <th className="px-4 py-3">{content.feeAmountCol}</th>
                  <th className="px-4 py-3">{content.refundAmountCol}</th>
                  <th className="px-4 py-3">{content.netAmountCol}</th>
                </tr>
              </thead>
              <tbody>
                {reconciliationRows.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="px-4 py-10 text-center text-sm text-muted">
                      {content.noReconciliation}
                    </td>
                  </tr>
                ) : (
                  reconciliationRows.map((row) => (
                    <tr key={`${row.day}-${row.merchantCode}`} className="border-t border-line/70">
                      <td className="px-4 py-4">{row.day}</td>
                      <td className="px-4 py-4">
                        <p className="font-medium text-foreground">{row.merchantName}</p>
                        <p className="mt-1 text-xs text-muted">{row.merchantCode}</p>
                      </td>
                      <td className="px-4 py-4">{row.incomeCount}</td>
                      <td className="px-4 py-4">{row.refundCount}</td>
                      <td className="px-4 py-4">{formatMoney(row.incomeAmount, "CNY", locale)}</td>
                      <td className="px-4 py-4">{formatMoney(row.feeAmount, "CNY", locale)}</td>
                      <td className="px-4 py-4">{formatMoney(row.refundAmount, "CNY", locale)}</td>
                      <td className="px-4 py-4 font-medium text-foreground">
                        {formatMoney(row.incomeAmount - row.feeAmount - row.refundAmount, "CNY", locale)}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className={`${panelClass} p-6`}>
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-muted">{content.settlementsEyebrow}</p>
          <h2 className="mt-2 text-2xl font-semibold text-foreground">{content.settlementsTitle}</h2>
        </div>

        <div className={`mt-6 ${tableWrapperClass}`}>
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-[#f3e7d7] text-xs uppercase tracking-[0.18em] text-muted">
                <tr>
                  <th className="px-4 py-3">{content.settlementDateCol}</th>
                  <th className="px-4 py-3">{content.merchantCol}</th>
                  <th className="px-4 py-3">{content.grossAmountCol}</th>
                  <th className="px-4 py-3">{content.feeAmountCol}</th>
                  <th className="px-4 py-3">{content.refundAmountCol}</th>
                  <th className="px-4 py-3">{content.adjustmentCol}</th>
                  <th className="px-4 py-3">{content.netAmountCol}</th>
                  <th className="px-4 py-3">{content.eligibleAtCol}</th>
                  <th className="px-4 py-3">{content.statusCol}</th>
                  <th className="px-4 py-3">{content.actionCol}</th>
                </tr>
              </thead>
              <tbody>
                {settlements.length === 0 ? (
                  <tr>
                    <td colSpan={10} className="px-4 py-10 text-center text-sm text-muted">
                      {content.noSettlements}
                    </td>
                  </tr>
                ) : (
                  settlements.map((settlement) => {
                    const netAmount = Number(settlement.netAmount.toString());

                    return (
                      <tr key={settlement.id} className="border-t border-line/70 align-top">
                        <td className="px-4 py-4 text-xs text-muted">
                          {formatDateTime(settlement.settlementDate, locale)}
                        </td>
                        <td className="px-4 py-4">
                          <p className="font-medium text-foreground">
                            {getMerchantDisplayName(settlement.merchant.name, locale)}
                          </p>
                          <p className="mt-1 text-xs text-muted">{settlement.merchant.code}</p>
                        </td>
                        <td className="px-4 py-4">{formatMoney(settlement.grossAmount.toString(), "CNY", locale)}</td>
                        <td className="px-4 py-4">{formatMoney(settlement.feeAmount.toString(), "CNY", locale)}</td>
                        <td className="px-4 py-4">{formatMoney(settlement.refundAmount.toString(), "CNY", locale)}</td>
                        <td className="px-4 py-4">{formatMoney(settlement.adjustmentAmount.toString(), "CNY", locale)}</td>
                        <td className="px-4 py-4 font-medium text-foreground">
                          {formatMoney(settlement.netAmount.toString(), "CNY", locale)}
                        </td>
                        <td className="px-4 py-4 text-xs text-muted">
                          <p>{formatDateTime(settlement.eligibleAt, locale)}</p>
                          <p className="mt-1">{content.paidAtPrefix} {formatDateTime(settlement.paidAt, locale)}</p>
                        </td>
                        <td className="px-4 py-4">
                          <StatusBadge tone={getSettlementStatusTone(settlement.status)}>
                            {getSettlementStatusLabel(settlement.status, locale)}
                          </StatusBadge>
                        </td>
                        <td className="px-4 py-4">
                          {canWriteFinance &&
                          settlement.status !== "PAID" &&
                          netAmount > 0 ? (
                            <form action={markSettlementPaidAction}>
                              <input type="hidden" name="settlementId" value={settlement.id} />
                              <input type="hidden" name="redirectTo" value="/admin/finance" />
                              <button
                                type="submit"
                                className="rounded-xl border border-line bg-white px-3 py-2 text-xs font-medium text-foreground"
                              >
                                {content.markPaid}
                              </button>
                            </form>
                          ) : (
                            <span className="text-xs text-muted">—</span>
                          )}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className={`${panelClass} p-6`}>
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-muted">{content.balanceEyebrow}</p>
          <h2 className="mt-2 text-2xl font-semibold text-foreground">{content.balanceTitle}</h2>
        </div>

        <div className={`mt-6 ${tableWrapperClass}`}>
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-[#f3e7d7] text-xs uppercase tracking-[0.18em] text-muted">
                <tr>
                  <th className="px-4 py-3">{content.balanceDateCol}</th>
                  <th className="px-4 py-3">{content.merchantCol}</th>
                  <th className="px-4 py-3">{content.openingBalanceCol}</th>
                  <th className="px-4 py-3">{content.income}</th>
                  <th className="px-4 py-3">{content.expenseCol}</th>
                  <th className="px-4 py-3">{content.closingBalanceCol}</th>
                </tr>
              </thead>
              <tbody>
                {balanceSnapshots.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="px-4 py-10 text-center text-sm text-muted">
                      {content.noBalance}
                    </td>
                  </tr>
                ) : (
                  balanceSnapshots.map((snapshot) => (
                    <tr key={snapshot.id} className="border-t border-line/70">
                      <td className="px-4 py-4 text-xs text-muted">
                        {formatDateTime(snapshot.snapshotDate, locale)}
                      </td>
                      <td className="px-4 py-4">
                        <p className="font-medium text-foreground">
                          {getMerchantDisplayName(snapshot.merchant.name, locale)}
                        </p>
                        <p className="mt-1 text-xs text-muted">{snapshot.merchant.code}</p>
                      </td>
                      <td className="px-4 py-4">{formatMoney(snapshot.openingBalance.toString(), "CNY", locale)}</td>
                      <td className="px-4 py-4">{formatMoney(snapshot.totalCredit.toString(), "CNY", locale)}</td>
                      <td className="px-4 py-4">{formatMoney(snapshot.totalDebit.toString(), "CNY", locale)}</td>
                      <td className="px-4 py-4 font-medium text-foreground">
                        {formatMoney(snapshot.closingBalance.toString(), "CNY", locale)}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className={`${panelClass} p-6`}>
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-muted">{content.ledgerEyebrow}</p>
          <h2 className="mt-2 text-2xl font-semibold text-foreground">{content.ledgerTitle}</h2>
        </div>

        <div className={`mt-6 ${tableWrapperClass}`}>
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="bg-[#f3e7d7] text-xs uppercase tracking-[0.18em] text-muted">
                <tr>
                  <th className="px-4 py-3">{content.ledgerTimeCol}</th>
                  <th className="px-4 py-3">{content.merchantCol}</th>
                  <th className="px-4 py-3">{content.typeCol}</th>
                  <th className="px-4 py-3">{content.directionCol}</th>
                  <th className="px-4 py-3">{content.amountCol}</th>
                  <th className="px-4 py-3">{content.referenceCol}</th>
                  <th className="px-4 py-3">{content.descriptionCol}</th>
                </tr>
              </thead>
              <tbody>
                {ledgerEntries.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="px-4 py-10 text-center text-sm text-muted">
                      {content.noLedger}
                    </td>
                  </tr>
                ) : (
                  ledgerEntries.map((entry) => (
                    <tr key={entry.id} className="border-t border-line/70 align-top">
                      <td className="px-4 py-4 text-xs text-muted">{formatDateTime(entry.occurredAt, locale)}</td>
                      <td className="px-4 py-4">
                        <p className="font-medium text-foreground">
                          {getMerchantDisplayName(entry.merchant.name, locale)}
                        </p>
                        <p className="mt-1 text-xs text-muted">{entry.merchant.code}</p>
                      </td>
                      <td className="px-4 py-4 font-mono text-xs text-foreground">
                        {getLedgerTypeLabel(entry.type, locale)}
                      </td>
                      <td className="px-4 py-4">
                        <StatusBadge tone={getLedgerTone(entry.direction)}>
                          {getLedgerDirectionLabel(entry.direction, locale)}
                        </StatusBadge>
                      </td>
                      <td className="px-4 py-4 font-medium text-foreground">
                        {formatMoney(entry.amount.toString(), entry.currency, locale)}
                      </td>
                      <td className="px-4 py-4 text-xs text-muted">
                        {entry.paymentRefund ? (
                          <>
                            <p className="font-mono text-foreground">{entry.paymentRefund.externalRefundId}</p>
                            <p className="mt-1">{entry.paymentOrder?.externalOrderId ?? "—"}</p>
                          </>
                        ) : entry.paymentOrder ? (
                          <>
                            <p className="font-mono text-foreground">{entry.paymentOrder.externalOrderId}</p>
                            <p className="mt-1">{entry.paymentOrder.channelCode}</p>
                          </>
                        ) : entry.settlement ? (
                          <>
                            <p className="font-mono text-foreground">{entry.settlement.id}</p>
                            <p className="mt-1">{formatDateTime(entry.settlement.settlementDate, locale)}</p>
                          </>
                        ) : (
                          "—"
                        )}
                      </td>
                      <td className="px-4 py-4 text-xs text-muted">{entry.description}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </section>
    </div>
  );
}
